### ISSUE TITLE
Please push 5.7.9 image to docker hub.

### ISSUE THREAD

**Issue by mysqlboy** [docker-library/mysql#111]

**Comment by yosifkit** [comment]
The [PR to official-images](https://github.com/docker-library/official-images/pull/1139) has merged, but it will take a little bit to build since there was also updates to the [debian base images](https://github.com/docker-library/official-images/pull/1140).  I'll try to ping you here once it is pushed to the Docker Hub.

**Comment by ltangvald** [comment]
Hi, 
Image is updated and ready for use :)

**Comment by yosifkit** [comment]
Yeah, it has been pushed. :tada:
