### ISSUE TITLE
Please update for 5.7.11+ to fix a bug

### ISSUE THREAD

**Issue by jar349** [docker-library/mysql#125]
I have a Vagrant environment that uses docker-compose plugin to stand up my application.  Using docker-compose because my app needs a mysql database and I'm linking them together.  Also using docker volume mounting to get access to the database files on the bare-metal machine.

Since this is in git, I have a mysql_data folder with a single .gitkeep file in it.  But now that the directory is not empty, mysqld --initialize-insecure fails.

[According to the documentation](http://dev.mysql.com/doc/refman/5.7/en/data-directory-initialization-mysqld.html), this is fixed as of MySQL 5.7.11.  Therefore, could you please make it available?

**Comment by yngvesv** [comment]
Hi, 5.7.11 is a not-yet-released maintenance update of the 5.7 series -- the manual may at times contain references like this, since documentation at MySQL happens in parallel with development and not in lock-step with what has actually been released. The currently released version is 5.7.9, which the current Docker image provides.

**Comment by jar349** [comment]
Thanks for sharing that; I'm embarrassed that I didn't check that to begin with.  I suppose that this can be closed.  I'm just sad that this is going to be annoying until then.  :-)
