### ISSUE TITLE
version 5.7 fails to apt-get install mysql-server='5.7.10-1debian8' 

### ISSUE THREAD

**Issue by mchekin** [docker-library/mysql#139]
Error on build:

> E: Version '5.7.10-1debian8' for 'mysql-server' was not found
> ERROR: Service 'mysql' failed to build: The command '/bin/sh -c {               echo mysql-community-server mysql-community-server/data-dir select '';          echo mysql-community-server mysql-community-server/root-pass password '';             echo mysql-community-server mysql-community-server/re-root-pass password '';            echo mysql-community-server mysql-community-server/remove-test-db select false;       } | debconf-set-selections      && apt-get update && apt-get install -y mysql-server="${MYSQL_VERSION}" && rm -rf /var/lib/apt/lists/\*  && rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql' returned a non-zero code: 100

It seems the version has been removed from the repo

**Comment by ltangvald** [comment]
Hi,

The change to 5.7.11 was merged in just this morning, so if you update your local tree it should build now.

**Comment by mchekin** [comment]
Don't you think it is better to remove the MYSQL_VERSION all together, since it would probably break again once they release the 5.7.12 version?

**Comment by yosifkit** [comment]
That is the point of that env; install the specified version or fail spectacularly. We are hard locked to a version so we don't accidentally update when we rebuild when the base image is updated.

**Comment by mchekin** [comment]
Sound heroic. But failing spectacularly is not great fun for people who use the image.

**Comment by tianon** [comment]
@mchekin what's your use case for building from the `Dockerfile` instead of using the pre-built images?

In the case of the official library, we have a [specific commit from this repository](https://github.com/docker-library/official-images/blob/c48c361bf249842c270528425365f45200ee2a45/library/mysql#L8) which is built and tagged as a particular version.  With that in mind, we need (for example) for commit `dbb83a94ee0a994651dd430d27caeac652cf9e78` to either build `5.7.14` or fail to build.  If upstream provided older versions in their APT repo, our build wouldn't _have_ to fail, but there's no way around that without upstream changing the way they create and manage their repository (and IMO that's not especially necessary -- we usually update within a fairly short amount of time).
