### ISSUE TITLE
Warn if using MYSQL_HOST

### ISSUE THREAD

**Issue by OscarBarrett** [docker-library/mysql#184]
As per [this MySQL bug](https://bugs.mysql.com/bug.php?id=31832) and [this related issue](https://github.com/docker-library/mariadb/issues/46), if you set MYSQL_HOST to anything other than localhost then initialization will fail. Because of the naming convention for variables used by this image (MYSQL_USER, MYSQL_PASSWORD etc) someone might try to use MYSQL_HOST for variable substitution in database configurations. As such it might be useful to warn users of this rather than initialization failing.

**Comment by tianon** [comment]
This is also related to #181 :cry:

IMO, this is something we ought to be documenting; perhaps there's some upstream MySQL documentation which explains which environment variables `mysqld`/`mysql` use that we could point to in a general "warning: be wary of environment variables which `mysql` uses (see docs at XYZ) since they can cause initialization to fail (for example, see XYZ bug link)" kind of blurb?

**Comment by yosifkit** [comment]
Here is the mysql documentation for all env vars in 5.6: https://dev.mysql.com/doc/refman/5.6/en/environment-variables.html

**Comment by tianon** [comment]
Looks like we can swap that 5.6 for 5.7 without any fanfare, too! :+1:

https://dev.mysql.com/doc/refman/5.7/en/environment-variables.html

**Comment by tianon** [comment]
Finally filed https://github.com/docker-library/docs/pull/1105. :+1:
