### ISSUE TITLE
Is it possible to run db script on image build rather that container start?

### ISSUE THREAD

**Issue by ivstas** [docker-library/mysql#194]
I have derivative docker build:
```
FROM mysql:5.5
# curl installation omitted
RUN curl -L http://someserver/migrations.sql > /docker-entrypoint-initdb.d/migrations.sql
```

In this case migration are being run **when I start** container. 
Is it possible to write such image that will run migrations **on image build** stage rather than container run?

**Comment by yosifkit** [comment]
Not easily.  You'll have to define a different datadir in my.cnf in order for the data to be stored in the image (since volumes are not saved).  This could also have performance issues, since the database files will be a part of the layered file-system (overlay, devicemapper, or aufs).  You'll also have to do a hacky `RUN` that starts mysql in the background and then runs the sql files.

**Comment by ltangvald** [comment]
You could maybe put a datadir with the sql executed on it inside the image. Then when starting the image check if the database exists, and if it doesn't copy it from inside the image to the more efficient volume location?
