### ISSUE TITLE
initdb fails when data volume on block store with extXfs

### ISSUE THREAD

**Issue by Ulexus** [docker-library/mysql#207]
Because extX filesystems create a `lost+found` directory in their root, you cannot initialize a MySQL database on the root of a block store which has been formatted to extXfs.  If you try, MySQL bombs out with:

```
Initializing database
2016-09-03T17:20:25.348234Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2016-09-03T17:20:25.348256Z 0 [ERROR] Aborting
```

An easy workaround would be to use a subdirectory of the block store.  Unfortunately, both of the ways one might do so are blocked by the current entrypoint script:

  - Mounting the volume to `/var/lib` instead of `/var/lib/mysql` causes the container to exit almost immediately, with no error logged.
  - Trying to change the DATADIR externally is pointless, because the entrypoint script overwrites it with whatever MySQL has been compiled with.

The simplest solution seems to me to only set DATADIR within the entrypoint script if it is NOT already set externally.   However, I don't know if MySQL tolerates non-default locations of its data directory.

**Comment by yosifkit** [comment]
Not sure why it would exit when mounting your ext file system to `/var/lib` (probably on the [datadir line](https://github.com/docker-library/mysql/blob/79c8b1e9ad710bf9a61b4957d3c6d925e3cfe716/5.7/docker-entrypoint.sh#L22-L27), since that is where we pipe to dev/null). It would fail to work anyway, since docker would bind mount a new volume inside that for the `mysql` directory and your ext file system would just have an empty folder.

This should be doable by mounting your "empty" ext file system at `/var/lib/mysql` (to prevent docker from allocating a volume there) and then adding `--datadir` to the docker run:
```console
$ docker run -d -v /ext/file/system/:/var/lib/mysql/ --name mysql -e MYSQL_ROOT_PASSWORD=12345 mysql --datadir=/var/lib/mysql/some-deeper-dir/`
```

**Comment by Ulexus** [comment]
Yes, I suspect that would probably be true.  So long as `--datadir` is honoured by the database init script (as you exhibited in #208), it is a trivial workaround.

Anyway, as #208 is not necessary, I don't think there is any preferable solution to this problem beyond simply using an alternate data directory.
