### ISSUE TITLE
passing --socket fails to initialize database

### ISSUE THREAD

**Issue by alvinr** [docker-library/mysql#238]
# Problem
This seems to be a generic problem in the MySQL *and* MariaDB images. If --socket is passed when the container is created then the database fails to initialize, for example

```
docker run -d -e MYSQL_ROOT_PASSWORD=foo mysql:5.6 --socket=/tmp/mysql.sock
```

The problem resides at round line 70 of docker-entrypoint.sh

``` 
mysql=( mysql --protocol=socket -uroot -hlocalhost)
```

This code will assume the default location of the socket file (e.g. /var/run/mysqld/mysqld.sock), and does not take into account the location specified in the command line.

# Solution
Ensure that any value from the command line is reflected in all potential uses of the mysql command.

**Comment by ltangvald** [comment]
A better solution might be to override the user's socket parameter when the server is started for init:

In general we pass any parameters set on the command line to the server, but not all server options are valid for the client, so we'd have to start filtering out options.

Since this client call is used to connect to the temporary server (started with --skip-networking) that is only used for database and user config, it doesn't need to use the socket location specified by the user.

**Comment by ltangvald** [comment]
Heh, I was confused about why this worked on 5.5. Checked the image and saw it doesn't have the socket path specified in any config file. From the docs: «The default location for the Unix socket file that the server uses for communication with local clients is /tmp/mysql.sock»
