### ISSUE TITLE
mysql:5.7 image - Issue mounting to AWS EBS volume

### ISSUE THREAD

**Issue by erstaples** [docker-library/mysql#252]
I have been experiencing a consistent issue with the mysql:5.7 image. When trying spin up a new Kubernetes pod and mount /var/lib/mysql to a brand new AWS EBS volume, I get the error message below. Switching to the mysql:5.6 image solves the issue, and the pod spins up and mounts the volume correctly.

It's also worth noting that this happens with existing mysql databases stored on EBS as well, but I thought it was especially strange to get this message with a brand new EBS volume.

```
2017-01-06T22:45:27.671338972Z 2017-01-06T22:45:27.671244Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2017-01-06T22:45:27.671343237Z 2017-01-06T22:45:27.671264Z 0 [ERROR] Aborting
```

**Comment by tianon** [comment]
Does your brand new EBS volume have any files in it already, such as a `lost+found` directory?  I'd honestly recommend using a sub-directory of your EBS volume to combat issues like this (and to allow for better flexibility in how you manage your data down the road), but otherwise you can try adding something like `--ignore-db-dir lost+found` to your `mysqld` invocation (ie on `docker run`).

**Comment by erstaples** [comment]
It does have a lost and found directory. adding `args: ['--ignore-db-dir=lost+found']` to my mysql k8s manifest fixed this issue for me
