### ISSUE TITLE
Disable SSL

### ISSUE THREAD

**Issue by manuelgu** [docker-library/mysql#256]
Hello, how does one disable SSL for a MySQL instance?

From MySQL wiki
`To prevent use of encryption and override other --ssl-xxx options, invoke the client program with --ssl-mode=DISABLED, --ssl=0, or a synonym (--skip-ssl, --disable-ssl)`
https://dev.mysql.com/doc/refman/5.7/en/using-secure-connections.html

**Comment by tianon** [comment]
Have you tried launching the image with `--ssl=0` to explicitly disable the server's SSL support?  If that doesn't work, then I'm afraid this will probably be something you'll have to create a custom configuration file for (to drop into the relevant `conf.d` directory inside an image that's built `FROM mysql:x.x`).

**Comment by ltangvald** [comment]
I general, you can pass any mysqld options on the command line to the Docker image, and they will be passed on to the server.

**Comment by manuelgu** [comment]
How would I pass the cli option?

**Comment by ltangvald** [comment]
Assuming you're starting from the command line, just add it to the end:
docker run [...] -d mysql:latest --ssl=0

**Comment by krisnik** [comment]
@manuelgu From cli i.e., the MySQL client, use the following command to connect without using ssl. 

mysql -u<user> -h<host>  --port<port> -p<password> --ssl-mode=DISABLED 

--ssl=0 is deprecated. instead use ssl-mode. You can switch to enabling ssl by using --ssl-mode=REQUIRED.

Thanks.

**Comment by manuelgu** [comment]
@krisnik Thanks!

The reason I want to disable it is because I'm getting
```
Thu Feb 02 20:23:40 GMT 2017 WARN: Establishing SSL connection without server's identity verification is not recomme                                                                                                        nded. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option is                                                                                                        n't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need eit                                                                                                        her to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```

everytime a connection is etablished. Modifying the connection string to provide `useSSL=false` on application level is not an option. Can I disable SSL and by that also extinguish that message?

**Comment by majidpal** [comment]
Was this issue resolved? I would like to disable in mysql:8.0.3

**Comment by majidpal** [comment]
so while connecting from Sonar  6.4 image to mysql:8.0.3, i have passed useSSL=false. Now I am not getting ssl error but getting below error -

2017.12.14 00:48:47 ERROR web[][o.s.s.p.Platform] Web server startup failed
java.lang.IllegalStateException: Can not connect to database. Please check connectivity and settings (see the properties prefixed by 'sonar.jdbc.').
        at org.sonar.db.DefaultDatabase.checkConnection(DefaultDatabase.java:108)
        at org.sonar.db.DefaultDatabase.start(DefaultDatabase.java:75)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Unknown system variable 'query_cache_size')

**Comment by tianon** [comment]
@majidpal yes, as @ltangvald noted above, simply add `--ssl=0` to your MySQL invocation

As for debugging why you can't connect to your running MySQL container, I'd recommend trying [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) (any of which should have a larger userbase who will see your question and might be able to help figure out what's wrong with your configuration).

I'm going to close this issue now, since the original request is solved (and there are no changes necessary to the image).
