### ISSUE TITLE
change on Foreign Key Modify behaviour (ER_FK_COLUMN_CANNOT_CHANGE)

### ISSUE THREAD

**Issue by mlarcher** [docker-library/mysql#283]
Version tagged 5.6.36 introduced a breaking change in the way MODIFY instruction on columns with a foreign key are handled: 
5.6.35 accepts the change, while 5.3.36 fails with a ER_FK_COLUMN_CANNOT_CHANGE error.
Can we assume that the image versioning respects semver and that this is just a mishap that should be fixed rapidly, or should we consider semver not to be of concern in the actual versioning scheme ?
And is this a case of "it's not a bug it's a feature", or will that be fixed soon ?

**Comment by ltangvald** [comment]
Is there an upstream bug report on bugs.mysql.com for this?

**Comment by mlarcher** [comment]
now there is at https://bugs.mysql.com/bug.php?id=86098&thanks=4

**Comment by tianon** [comment]
Closing given that this appears to have been an intentional change by upstream, and not something introduced by (or fixable in) this Docker image.  If there's a reliable way to reproduce the issue, I'd recommend updating that with upstream describing how to do so (since it appears that the issue above was closed due to inactivity waiting for a reproducer).
