### ISSUE TITLE
Container with MySQL crash almost every day

### ISSUE THREAD

**Issue by ethervoid** [docker-library/mysql#29]
One of the multiple containers i have is a MySQL database but i have this stability problem. Almost every day the container is down and i have to restart it.

I've been looking in the logs for some clue about the problem but i didn't found anything.

I have containers with nginx and wordpress and i don't have any problem.

I can provide whatever log you need.

Thank you :)

**Comment by bentruyman** [comment]
I've experienced precisely the same problem and it was due to a RAM constraint. The application I run typically consumes fairly little RAM (~200MB) but bursts periodically up to over 500MB. During these bursts, the MySQL container (which consumed ~470MB) would consistently crash. As my host only had 1GB total RAM, bumping up to 2GB has so far resolved the issue.

Not sure if this is an issue with this image in particular, but it was difficult to track down. In fact the RAM issue only "clicked" while I happened to glance at `top` during one of the bursts I described above... :cry:

**Comment by thaJeztah** [comment]
the default settings of MySQL can be quite memory-hungry. While great for performance, depending on your use case (and environment), you may have to tweak the settings (I.e running with your own configuration file); for an earlier discussion on this, see https://github.com/docker-library/mysql/issues/3

**Comment by qedrakmar** [comment]
Since this issue appears to be untouched, and as mentioned in #3 , related to the the underlying system instead of an issue with the image, I am closing this.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
