### ISSUE TITLE
mysql_ssl_rsa_setup: Can't change permissions of the file 'ca-key.pem'

### ISSUE THREAD

**Issue by afshinm** [docker-library/mysql#302]
I'm using mysql v5.7 image in my Kubernetes and a weird issue happens when I create the pod for the first time. 

```
Database initialized
Initializing certificates
Generating a 2048 bit RSA private key
..............+++
.....................................................................................................+++
unable to write 'random state'
writing new private key to 'ca-key.pem'
-----
Generating a 2048 bit RSA private key
................+++
............................+++
unable to write 'random state'
writing new private key to 'server-key.pem'
-----
Generating a 2048 bit RSA private key
.......................................+++
.........+++
unable to write 'random state'
writing new private key to 'client-key.pem'
-----
mysql_ssl_rsa_setup: Can't change permissions of the file 'ca-key.pem' (Errcode: 1 - Operation not permitted)
2017-06-13 14:29:12 [ERROR]   Error setting file permissions forca-key.pem and ca.pem
mysql_ssl_rsa_setup: Can't change permissions of the file 'server-key.pem' (Errcode: 1 - Operation not permitted)
2017-06-13 14:29:12 [ERROR]   Error setting file permissions forserver-key.pem and server-cert.pem
mysql_ssl_rsa_setup: Can't change permissions of the file 'client-key.pem' (Errcode: 1 - Operation not permitted)
2017-06-13 14:29:12 [ERROR]   Error setting file permissions forclient-key.pem and client-cert.pem
```

and then Kubernetes restarts the pod immediately because of this error. 

I'm using Azure file storage for `/var/lib/mysql`. Apparently, the issue is this line: https://github.com/docker-library/mysql/blob/master/5.7/docker-entrypoint.sh#L97

Does anyone know what is going on? AFAIK, Docker creates the container with `root` so I'm not sure what is this error?

**Comment by yosifkit** [comment]
While the container is launched as root, the entrypoint script does a chown and then drops to the mysql user.  It seems that this user cannot change permissions of the ssl key files it generates in `/var/lib/mysql`. :confused:   Maybe try running the container as the user that owns the directory used from the Azure file storage (something other than root)?

**Comment by afshinm** [comment]
@yosifkit I see, thanks for this. Actually, I have the exact same K8s deployment file and the same storage settings on another cluster, and works fine. Let me try what you suggested and I will update this thread.

**Comment by afshinm** [comment]
I tried what you suggested @yosifkit, but no luck. Eventually, I changed the image version to `mysql:5.7.16` and now it is working fine. Sorry to disappoint you 😞

**Comment by tianon** [comment]
@afshinm your issue is successfully solved -- no disappointment here! :smile: :+1: :heart:

**Comment by iankittomar** [comment]
![my](https://user-images.githubusercontent.com/34299541/44657949-0591dc80-a9ff-11e8-9cad-c68d8bff38e3.png)

Getting similar issues, I am Mounting MySQL volume on samba share cifs (/mnt/docker/mysql)
MySQL version = 8.0.12

**Comment by Allendorf231** [comment]
@iankittomar Did you find a solution for this, currently running to the same problem… Cheers

**Comment by ntoljic** [comment]
Just hit the same issue as well, also with a CIFS share. The problem is that CIFS apparently does not support Linux file permissions and thus the container setup fails.
I also tried placing the files in the share before starting the container, but then the setup fails as it expects to find an empty directory...

**Comment by chirangaalwis** [comment]
> I tried what you suggested @yosifkit, but no luck. Eventually, I changed the image version to `mysql:5.7.16` and now it is working fine. Sorry to disappoint you

@afshinm I encountered the same issue when using the official Docker Library MySQL image version `5.7.31` with the latest, version `1.6.7` [stable MySQL Helm chart](https://hub.helm.sh/charts/stable/mysql).

**Comment by Angelinsky7** [comment]
i've got the same issue on Windows 10 with WSL2 Debian....
my simple config : 

```
version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2342kj34u23jh4k2342
      MYSQL_DATABASE: db_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: sn234jk2lfsdf823sdfs
```

**Comment by yosifkit** [comment]
@Angelinsky7, it is likely permissions problems caused by sharing files across the host/VM boundary (https://github.com/docker/for-win/issues/4824). A named docker volume should just work and still give you the persistence that you need.

```yaml
    volumes:
      - mysql-data:/var/lib/mysql
```

**Comment by Angelinsky7** [comment]
@yosifkit thanks for you answer. But i don't want to use a docker volume. I want to use a mount bind.
So the workaround i found is to start the image from windows command line (without using wsl2), waiting for mysql to create all dirs and files then stopping it and re-running it from wls2.
This is not great at all and feels like a hack but i can make it work like that.

**Comment by vietor** [comment]
Try command add "--skip-ssl --sha256-password-auto-generate-rsa-keys=OFF --caching-sha2-password-auto-generate-rsa-keys=OFF"

**Comment by wilson0x4d** [comment]
While some online resources claim that the uid and gid of the mysql account are "27", after poking at the latest image (8.0.33) I found the uid/gid were "999" -- perhaps this changed at some point.

```sh
sh-4.4# cat /etc/passwd
...redacted...
mysql:x:999:999::/var/lib/mysql:/bin/bash

sh-4.4# id mysql
uid=999(mysql) gid=999(mysql) groups=999(mysql)
```

At first I tried making everything world-readable, but this resulted in the same problems others described.

To correct this issue I only needed to change my mount options to specify the correct gid/uid values:

```yaml
  mountOptions:
    - dir_mode=0770   # nothing needs to be world readable!
    - file_mode=0770  # nothing needs to be world readable!
    - uid=999
    - gid=999
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
```

There was no need to `--skip-ssl` nor pass any other security-related args in, I did not need to switch to NFS, in my case I am mounting a SMB-based Azure Files share via CIFS module, container is running within a k8s pod.

Hope this helps someone else. 👍

**Comment by cheefi** [comment]
@wilson0x4d do u mind sharing where should i set these

  ```
mountOptions:
    - dir_mode=0770   # nothing needs to be world r/w!
    - file_mode=0770  # nothing needs to be world r/w!
    - uid=999
    - gid=999
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
```

**Comment by jianlianxi** [comment]
Windows 10 with WSL2 docker desktop runs mysql image to mount the database. Selecting the linux subsystem directory can avoid permission issues.

**Comment by wilson0x4d** [comment]
> @wilson0x4d do u mind sharing where should i set these
> 
> ```
> mountOptions:
>   - dir_mode=0770   # nothing needs to be world r/w!
>   - file_mode=0770  # nothing needs to be world r/w!
>   - uid=999
>   - gid=999
>   - mfsymlinks
>   - cache=strict
>   - nosharesock
>   - nobrl
> ```

sorry for the late reply, but in case it helps others OP was in regards to Kubernetes configuration. `mountOptions` is a config section for the "Persistent Volume" resource type in k8s. More info about PV configuration can be found here https://kubernetes.io/docs/concepts/storage/persistent-volumes/

If others have this outside of k8s (NAS-connected volumes/directories for example) then the solution may be similar, but the fix will have nothing to do with the example config I provided. Instead you may need to `chown` the files with a matching uid/gid, or in the case of unix/unix-like systems you may need to change the mount flags in fstab or similar (since those typically override the uid/gid data being seen by programs accessing the volume.)

If you have this problem under WSL and the 'volume' is actually a mounted non-unix host folder from windows then `chown` won't work since Windows ignores fs attributes like owner/group info, it will just identify as root:root (0:0) and mysql of course wouldn't have access. As @jianlianxi suggested putting mysql datadir onto the WSL subsystem fs would allow you to control permissions. The only problem with that approach is you have no volume mount managed through the container interface, and, you're hackishly relying on a WSL implementation detail (that the location on the subsystem root is persistent), but, if it works and it's for development 🤷‍♂️ it works.
