### ISSUE TITLE
Hi I am trying to connect jira container with mysql container. both container are from same centos image and on same host.

### ISSUE THREAD

**Issue by samratBasra** [docker-library/mysql#305]
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                  PORTS                    NAMES
26785caefac8        centos              "/bin/bash"              About an hour ago   Up About an hour        0.0.0.0:8080->8080/tcp   jira
1fdda42620ca        centos              "/bin/bash"              16 hours ago        Up 16 hours             0.0.0.0:3306->3306/tcp   mysql

while accessing mysql server form jira, getting below error. 
null, message from server: "Host 'gateway' is not allowed to connect to this MySQL server"

**Comment by ltangvald** [comment]
Hi,
Generally, a MySQL user is a combination of username and host, so to be able to connect from a remote host "gateway", you need a user 'username'@'gateway' created on the server (the error is the same is username does not exist).

You can run SELECT user, host FROM mysql.user; to get a list of current users

**Comment by tianon** [comment]
Closing, since this appears solved.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
