### ISSUE TITLE
Getting a trigger on sql import completion

### ISSUE THREAD

**Issue by chinchang** [docker-library/mysql#308]
I am using the recommended syntax to import a SQL file in the container, like so:

`- ./dump.sql:/docker-entrypoint-initdb.d/sql1.sql`

Now I have a big SQL file. So when I run `docker-compose up -d`, the command gets completed quickly but behind the scenes the SQL importing is still running. So even after `docker-compose up -d` I have to wait for some indefinite time before actually being able to use my container.

Is there some way to get some sort of message/trigger that all sql imports have finished inside the container?

**Comment by yosifkit** [comment]
No message or trigger, but once the sql port is listening and responding remotely, the server is ready.  We usually solve this with a short script to wait for the database connection to be ready (like [wordpress](https://github.com/docker-library/wordpress/blob/648a2715dad185ad90155350b48f190b3f95ae21/php7.1/apache/docker-entrypoint.sh#L190-L201)).

**Comment by ltangvald** [comment]
For the upstream images, I've made (it's not released yet) a simple little healthcheck script that checks two things:
* That the file /mysql-init-complete exists (this file is touched before the main server process is started, so after all the init operations)
* That mysqladmin ping returns 0

The biggest issue with it is that while mysqladmin ping will return 0 even if it can't actually log in, a failed login will create an "access denied" entry in the server log, so by default we will create a healthchecker@localhost user that has no privileges. But overall I think it works pretty well, and would allow dependent containers to check the health status instead of having a wait script.

**Comment by chinchang** [comment]
@yosifkit @ltangvald Thanks for your response! I guess manual monitoring is the way to go then.
@ltangvald I'll look forwarf to your healthscript.

Meanwhile I am going forward with this script which checks the final application response code:

```

# Create containers
docker-compose up -d

# Check if website is up

echo "\033[33mWebsite will auto-open when its up. Checking status...\033[0m";

while true;
do
 status=`curl -s -o /dev/null -Ik -w "%{http_code}" https://local.com`

 if [ $status -eq "200" ]; then
  echo "\033[32mYuhoo! Website is up!\033[0m"
  open https://local.com
  break;
 else
  printf ".";
  sleep 4;
 fi
done
```
