### ISSUE TITLE
Unable to build MySQL 5.7

### ISSUE THREAD

**Issue by taolive** [docker-library/mysql#341]
docker build -t mysql_test .

W: Failed to fetch http://repo.mysql.com/apt/debian/dists/jessie/InRelease  Unable to find expected entry 'mysql-5.7-dmr/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c { 		echo mysql-community-server mysql-community-server/data-dir select ''; 		echo mysql-community-server mysql-community-server/root-pass password ''; 		echo mysql-community-server mysql-community-server/re-root-pass password ''; 		echo mysql-community-server mysql-community-server/remove-test-db select false; 	} | debconf-set-selections 	&& apt-get update && apt-get install -y mysql-server="${MYSQL_VERSION}"* && rm -rf /var/lib/apt/lists/* 	&& rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql' returned a non-zero code: 100

**Comment by ltangvald** [comment]
You seem to be using a very old mysql.list file, with the mysql-5.7-dmr repo, which no longer exists. Try simply changing mysql-5.7-dmr to mysql-5.7

**Comment by tianon** [comment]
Closing due to lack of response.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
