### ISSUE TITLE
unable connect mysql 8.0 container from host while it start with a specific cnf on host machine

### ISSUE THREAD

**Issue by a1237a** [docker-library/mysql#354]
OS : CentOS7
image:mysql 8.0

docker run --name mysql8 -p 3307:3306 -v /data/docker_mysql:/var/lib/mysql -v /data/mysql_cnf:/etc/mysql/conf.d -e MYSQL_ROOT_PASSWORD=123456 -d mysql:8.0

specific cnf:
[mysqld]
federated
skip-grant-tables
connect from host:
[root@xx-xx-xx-xx mysql_cnf]# mysql -uroot -P3307 -hxx.xx.xx.xx 
ERROR 2003 (HY000): Can't connect to MySQL server on 'xx.xx.xx.xx' (111)

docker run --name mysql82 -p 3308:3306 -v /data/docker_mysql2:/var/lib/mysql  -e MYSQL_ROOT_PASSWORD=123456 -d mysql:8.0
default cnf : And it can connect well from host machine.

**i try so hard and dont konw y. then i use image 5.7 for test.**
the specific cnf:
[mysqld]
federated
skip-grant-tables

docker run --name mysql83 -p 3309:3306 -v /data/docker_mysql3:/var/lib/mysql -v /data/mysql_cnf:/etc/mysql/conf.d -e MYSQL_ROOT_PASSWORD=123456 -d mysql:latest

[root@xx-xx-xx-xx mysql_cnf]# mysql -uroot -P3309 -hxx.xx.xx.xx
and it can connect well on host machine.

**Comment by tianon** [comment]
I'm not entirely convinced this is an issue with the Docker image -- if anything, it looks like an issue with 5.7 vs 8.0 upstream. :confused:

Have you tried using command line flags instead of bind-mounting over `/etc/mysql/conf.d`? (`docker run ... mysql:8.0 --federated`, etc)

Have you done a `docker pull` to ensure you've got the latest available image?

**Comment by a1237a** [comment]
Have you tried using command line flags instead of bind-mounting over /etc/mysql/conf.d? (docker run ... mysql:8.0 --federated, etc)
never tried . i dont konw how to do that.

Have you done a docker pull to ensure you've got the latest available image?
8.0 and 5.7 were both latest available image at that time

**Comment by tianon** [comment]
I'd recommend turning to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) for further help debugging this. :+1:

(Closing since it doesn't seem to be an issue with the image.)
