### ISSUE TITLE
Does not support `load data infile`?

### ISSUE THREAD

**Issue by yarcowang** [docker-library/mysql#38]
```
mysql> load data infile '/var/www/html/proj/fixture/20141230.csv' REPLACE INTO TABLE customer;
ERROR 13 (HY000): Can't get stat of '/var/www/html/proj/fixture/20141230.csv' (Errcode: 2)
mysql> load data local infile '/var/www/html/proj/fixture/20141230.csv' REPLACE INTO TABLE customer;
ERROR 1148 (42000): The used command is not allowed with this MySQL version
```

**Comment by tianon** [comment]
Can you give us a little more detail?  What version of the image are you running?

**Comment by yarcowang** [comment]
@tianon 

```
mysql                      latest              a385835786ac        7 weeks ago         236 MB
mysql                      5.5                 0946e3048fc1        7 weeks ago         215.2 MB
```

**Comment by thaJeztah** [comment]
@yarcowang You'll probably have to *enable* `LOAD DATA INFILE` in your configuration file. See [this answer on StackOverflow](http://stackoverflow.com/questions/10762239/mysql-enable-load-data-local-infile)

Enabling that function has some possible security implications, that's why disabling it is a sensible default (see [Security Issues with LOAD DATA LOCAL](http://dev.mysql.com/doc/refman/5.5/en/load-data-local.html) in the MySQL documentation)


..however, the same page of the [MySQL documentation](http://dev.mysql.com/doc/refman/5.5/en/load-data-local.html) mentions;

> By default, all MySQL clients and libraries in binary distributions are compiled with the -`DENABLED_LOCAL_INFILE=1` option, to be compatible with MySQL 3.23.48 and before.

@tianon I think the default here is the "better" (safer) one, but it differs from the documentation if this is an official "binary distribution" (?)

**Comment by yosifkit** [comment]
For `mysql:5.5`, we just download the zip of binary files, so the docs must be wrong for how they compile it now.  So I think the StackOverflow answer you linked would be the correct workaround (I would go with the second one and make a my.cnf file and mount it into the container).

**Comment by thaJeztah** [comment]
Yes, I *thought* it was compiled from source, then saw it was just a download :)

I agree, changing the my.cnf is the better option; safer by default.

@yarcowang I think you have your answer, is it okay to close this issue?

**Comment by yarcowang** [comment]
@thaJeztah i think so.

**Comment by thaJeztah** [comment]
@yarcowang thanks! I hope you get it to work. If you need further assistance, I think there will be people able to give you some hints in the #docker IRC channel

**Comment by yarcowang** [comment]
thank you.
