### ISSUE TITLE
Simplify configuration files tree

### ISSUE THREAD

**Issue by federico-razzoli** [docker-library/mysql#390]
A manual inspection to look for an option takes an unreasonable amount of time.

**Comment by yosifkit** [comment]
Those are mostly inherited from the mysql packages for Debian; we only add `docker.cnf`:

https://github.com/docker-library/mysql/blob/30bf2b7ff3010d1f2ee89967dd1303d6a7230c51/5.7/Dockerfile#L64-L69

Most MySQL config can be specified later to override an earlier value:

```console
$ docker run -d -e MYSQL_ROOT_PASSWORD=12345 mysql:5.7 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
```

**Comment by santec** [comment]
This adds complexity, it's extremely error prone and it's hard to automate. It's better to reduce the number of files. But it would be nice if a simpler structure is provided by the image itself.

Ideally, from a user point of view, it would be even nicer to have the same structure in mysql image and mariadb image.

**Comment by ltangvald** [comment]
For the older versions, the structure was originally created in Debian because MariaDB also uses "mysql" file paths, so MySQL would have config in /etc/mysql/mysql.conf.d, MariaDB in /etc/mysql/mariadb.conf.d/, and shared options would be in /etc/mysql/conf.d/
So it's legacy of using the standard Debian packages, and I agree it's a bit much for the more self-contained Docker images.

However, the server itself only cares about /etc/mysql/my.cnf, so it's possible to change, and we did for 8.0.
The 8.0 images use the core packages that include no config, so we have a slightly simpler structure:
https://github.com/docker-library/mysql/tree/master/8.0/config

Does that look better to you?

**Comment by santec** [comment]
Of course, this looks good. It's also very good that you reduced the number of settings in the files.

Any plans to port this to 5.7?
