### ISSUE TITLE
After upgrade Docker, cannot open table

### ISSUE THREAD

**Issue by KingWu** [docker-library/mysql#417]
docker-mysql: 5.7
Docker: From 17.03.1-ce-mac12 to 18.03.0-ce-mac60 (23751)

After i upgrade Docker, i found that i will get this error when querying data for this table.

[Warning] InnoDB: Cannot open table from the internal data dictionary of InnoDB though the .frm file for the table exists. Please refer to http://dev.mysql.com/doc/refman/5.7/en/innodb-troubleshooting.html for how to resolve the issue.

Any one know this issue?

Thanks

**Comment by tianon** [comment]
This sounds like some of MySQL's files have been lost -- did you do a clean shutdown of MySQL before upgrading?  From what I could find on this particular error, you might be able to rename the offending `.frm` file to `.bak`, butt that's probably not the ideal solution.  I'd probably recommend instead starting fresh from your most recent backup.

Since this isn't really anything specific to (or that we could fix in) the image, I'm going to close.  In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!

**Comment by stefanocog** [comment]
@KingWu i have same problem, you have resolved?

**Comment by KingWu** [comment]
@stefanocog Cannot resolved. I used my backup for recovery

**Comment by kkker** [comment]
Thats work for me,
https://stackoverflow.com/a/42741757

Long story short,
1. Stop mysql.
2. To move .ibd files of database folder to tmp folder.
3. Start mysql and make sure mysql running,
4.Stop mysql for revert .ibd files from tmp folder to the database folder.
5. finial to start mysql.

Good luck!

**Comment by ThomasGHenry** [comment]
I think the issue is that when the container stops, it kills mysql violently. Some intervention on the part of the image might soften that, but I'm not sure what that would look like.

**Comment by ThomasGHenry** [comment]
This would need to be thought through fully. I didn't even test it, but is there a reason not to do something like this?

https://github.com/ThomasGHenry/mysql/commit/34c48e9d74ed9959c9d8a0a93e257967eab21c5b

**Comment by theothermattm** [comment]
For anyone else who comes upon this issue, I _believe_ the root cause is this issue: https://github.com/docker-library/mysql/issues/47

And a sensible workaround is specifically in this comment: https://github.com/docker-library/mysql/issues/47#issuecomment-147397851
