### ISSUE TITLE
MySql container isn't picking up modified max_allowed_packet value from custom my.conf file

### ISSUE THREAD

**Issue by ramizrshaik** [docker-library/mysql#420]
Hi

I am using MySQL:5.7 image for my sonarqube db. recently upgraded sonarqube version from 6.4 to 7.0 version. After that MySQL db global variable 'max_allowed_packet' isnt picking up my custom change. Any thoughts on this?

**Comment by tianon** [comment]
You'll need to provide more detail about how you're running, etc for folks to help with your issue.  It's also possible sonarqube itself updated this value directly in your database instance.

If you're using a drop-in configuration file, ensure it's in a place MySQL is actually looking during startup.  What I'd probably recommend thinking about doing instead is using startup parameters, since they're more explicit:
```console
$ docker run ... mysql:5.7 --max_allowed_packet=xxx
```

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
