### ISSUE TITLE
Problem with DB after factory reset

### ISSUE THREAD

**Issue by Staniak** [docker-library/mysql#442]
Hi,
i have problem with my mysql after factory reset in docker. My DB in now broken.
I don't have any tables in phpmyadmin, and a lot of errors when im trying add user, or add table. 
Im not a pro in docker things, but it was working well. :(

![image](https://user-images.githubusercontent.com/28866674/41396801-58d977a4-6fb2-11e8-9ef3-5698a0687294.png)
![image](https://user-images.githubusercontent.com/28866674/41396864-8dce284c-6fb2-11e8-9626-52f213cf0fe9.png)
Docker-compose.yml
![image](https://user-images.githubusercontent.com/28866674/41396901-aea856aa-6fb2-11e8-8268-0fe498bd8735.png)

**Comment by wglambert** [comment]
What do you mean by "factory reset", if you remove the container then anything not mounted as a volume is gone. In this case if you do `docker-compose down` then your containers are removed. If you do `docker-compose stop` then they're stopped without being removed

So your mysql has a volume mounted for the data directory, any database files should be there. With your phpmyadmin there isn't a volume specified.

As for the error of the definer user not existing, I found https://github.com/docker-library/mysql/issues/380#issuecomment-384135863
>so I think it's worth pointing out that the solution, of course, is just to run mysql_upgrade

Here's another thread that might help you with that https://github.com/docker-library/mysql/issues/130#issuecomment-264952386

The issue seems like a usability one rather than an actual error with the image, so you could try [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) for more help.

**Comment by Staniak** [comment]
In docker setting there is an option called factory reset. It flush all images and containers. 

After mysql_upgrade  i got error: 
mysql_upgrade: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) while connecting to the MySQL server
Upgrade process encountered error and will not continue.
