### ISSUE TITLE
"exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by osenlin** [docker-library/mysql#443]
exec this code 
```
docker run --rm -d -e MYSQL_ROOT_PASSWORD=root mysql:tag
```  
but get   
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"docker-entrypoint.sh\": executable file not found in $PATH": unknown.

**Comment by wglambert** [comment]
Is this related https://github.com/docker-library/postgres/issues/296

**Comment by rajesh2531** [comment]
The reason is the ' docker-entrypoint.sh' does not have executable permission. You either need to add executable permission for the file present in your working directory where you build docker file or add chmod command to change the permission of the file in Dockerfile after you copied the file to /usr/local/bin/.

**Comment by stuffyAI** [comment]
One does not simply spend 1 hour searching for a solution only to have it answered by a minion on a closed issue
