### ISSUE TITLE
how to insert default database 

### ISSUE THREAD

**Issue by ww110052181** [docker-library/mysql#450]
how to modify file  entrypoint.sh

**Comment by ww110052181** [comment]
insert the default database like as like as performance_schema,information_schema

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance

> When a container is started for the first time, a new database with the specified name will be created and initialized with the provided configuration variables. Furthermore, it will execute files with extensions `.sh`, `.sql` and `.sql.gz` that are found in `/docker-entrypoint-initdb.d`. Files will be executed in alphabetical order. You can easily populate your `mysql` services by [mounting a SQL dump into that directory](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume) and provide [custom images](https://docs.docker.com/reference/builder/) with contributed data. SQL files will be imported by default to the database specified by the `MYSQL_DATABASE` variable.

**Comment by wglambert** [comment]
Closing since the question is answered

If you have further questions you should ask [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repositories are for issues with the image and not necessarily for questions of usability
