### ISSUE TITLE
docker-entrypoint.sh silent exits on docker compose run

### ISSUE THREAD

**Issue by FernandoMiguel** [docker-library/mysql#462]
`$ docker-compose run mysql /entrypoint.sh`
> Creating volume "devs-docker_mysql" with default driver

and then immediately exits.

was expecting for the db to be initialised and then exit

**Comment by wglambert** [comment]
What do the logs say, did you pass the `MYSQL_ROOT_PASSWORD` variable

**Comment by wglambert** [comment]
Closing since the issue isn't certain and there's no followup

You could also try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repositories are for issues with the image and not necessarily for questions of usability
