### ISSUE TITLE
Docker Compose: Unable to run mysql, it will stop automatically.

### ISSUE THREAD

**Issue by Hiolen** [docker-library/mysql#482]
## mysql will stop automatically
All my settings are working. 

Yesterday I encounter a problem that my mysql is not working anymore. If I up my  docker `docker-compose up -d` the mysql will run just a seconds and it will stop automatically.

See my logs
<img width="1280" alt="screen shot 2018-08-31 at 10 51 12" src="https://user-images.githubusercontent.com/40222158/44894940-b6141f00-ad24-11e8-9b6b-017172421ec8.png">

<img width="848" alt="screen shot 2018-08-31 at 11 22 18" src="https://user-images.githubusercontent.com/40222158/44894962-c88e5880-ad24-11e8-9e49-fae1fce8c8ac.png">

I already try this solution 
https://dba.stackexchange.com/questions/163445/innodb-ignoring-the-redo-log-due-to-missing-mlog-checkpoint at some point, it's still not working.

Is there anyone who encounter this problem and can you please guide me how to fix this. Thanks!

**Comment by ltangvald** [comment]
Could you try the workaround offered here https://bugs.mysql.com/bug.php?id=85307 ?

**Comment by wglambert** [comment]
Since there doesn't seem to be anything denoting an error with the image I'm going to close.

If you have further questions you should ask [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repositories are for issues with the image and not necessarily for questions of usability
