### ISSUE TITLE
docker-entrypoint-initdb.d data not executed

### ISSUE THREAD

**Issue by BZaldua** [docker-library/mysql#493]
I made a Docker Compose using MySQL 5.6 and a volume to load the data I need. As written in the documentation, the script I want to be executed is inside docker-entrypoint-initdb.d and everything works correctly. The issue comes when I try the same Compose with a different user (or computer).

The script is not executed even though the file is found inside the entrypoint directory. I tried coping the Dockerfile and creating my own image but the issue persists. I added some echos to see if the code below is executed and nothing. I tried deleting the volumes too but nothing.

```
for f in /docker-entrypoint-initdb.d/*; do
        echo "inside docker-entrypoint-initdb.d FOR"
	process_init_file "$f" "${mysql[@]}"
done
```
The echo and the process_init_file functions are not executed. Any idea why this is happening?

**To leave things clear, I already tried this:**
1. Delete image and volumes. Then restart the service.
2. Run the script inside the container.
3. Use the official image found in Docker Hub.

**Comment by ltangvald** [comment]
Are you mounting a named volume for the data?
The scripts in there are only executed if the data directory is empty, i.e. when initializing a new database from scratch.

**Comment by tianon** [comment]
My only guess is something to do with permissions and/or the volume sticking around and getting re-used from one user account to another (thus not re-executing the `initdb` steps because the database already exists).

Regardless, this is definitely something environmental happening in your system -- there's nothing in the image that would or could prevent the `initdb` behavior from happening except permissions (ability to read the `initdb` files) or a pre-existing database (such that the entrypoint itself will not even attempt to run the `initdb` files).
