### ISSUE TITLE
Add to expose port 33061

### ISSUE THREAD

**Issue by stanislas-prime** [docker-library/mysql#502]
Add port 33061 to Dockerfile

Before
EXPOSE 3306 33060

After
EXPOSE 3306 33060 33061

**Comment by yosifkit** [comment]
`EXPOSE` is really just letting the user know what this image would use in the default case and has no bearing on what port the container may be available on (since it could be mapped to a different port on the Docker host).

`mysqld` doesn't listen on this port by default, so this is not needed. The port can vary based on the value of the `group_replication_local_address` since `33061` is only the [recommended port](https://dev.mysql.com/doc/refman/8.0/en/group-replication-configuring-instances.html#group-replication-configure-plugin)

```console
$ docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=12345 mysql:8
....
$ nmap -p 3306,33060,33061 172.17.0.4
Starting Nmap 7.70 ( https://nmap.org ) at 2018-10-08 16:46 PDT
Nmap scan report for 172.17.0.4
Host is up (0.000082s latency).

PORT      STATE  SERVICE
3306/tcp  open   mysql
33060/tcp open   mysqlx
33061/tcp closed unknown

Nmap done: 1 IP address (1 host up) scanned in 0.05 seconds
```
