### ISSUE TITLE
mysqld: Can't create directory '/var/lib/mysql/' (Errcode: 17 - File exists)

### ISSUE THREAD

**Issue by xpalm** [docker-library/mysql#528]
root@master01:~# kubectl logs mysql-599c5576dd-w8p55
Initializing database
mysqld: Can't create directory '/var/lib/mysql/' (Errcode: 17 - File exists)
2018-12-26T07:54:53.985516Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-12-26T07:54:53.991096Z 0 [ERROR] Aborting

root@master01:~# helm status mysql
LAST DEPLOYED: Tue Dec 25 23:54:16 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Deployment
NAME   DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
mysql  1        1        1           0          2m26s

==> v1/Pod(related)
NAME                    READY  STATUS            RESTARTS  AGE
mysql-599c5576dd-w8p55  0/1    CrashLoopBackOff  4         2m26s

==> v1/Secret
NAME   TYPE    DATA  AGE
mysql  Opaque  2     2m26s

==> v1/ConfigMap
NAME        DATA  AGE
mysql-test  1     2m26s

==> v1/PersistentVolumeClaim
NAME   STATUS  VOLUME  CAPACITY  ACCESS MODES  STORAGECLASS  AGE
mysql  Bound   mypv1   100Gi     RWO           2m26s

==> v1/Service
NAME   TYPE       CLUSTER-IP   EXTERNAL-IP  PORT(S)   AGE
mysql  ClusterIP  10.111.57.1  <none>       3306/TCP  2m26s

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by yosifkit** [comment]
Can you give a minimal reproducer? (ie, one that just uses `docker run` or possible a `docker-compose` yaml, and doesn't involve a whole Kubernetes cluster with Helm)

(My guess from the error is that it sounds like your helm chart is mounting a file at `/var/lib/mysql` rather than a folder.)

**Comment by wglambert** [comment]
Since there isn't anything denoting an error with the image I'm going to close. If you do find something otherwise then I can re-open if needed.

If you have other questions you could try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repositories are for issues with the image and not necessarily for questions of usability
