### ISSUE TITLE
Access denied for user 'root'@'localhost' when using port 3306

### ISSUE THREAD

**Issue by wang97td** [docker-library/mysql#584]
hi,
I run a mysql container binding port 3306 in my localhost (windows 10 system) .
`docker run -d --name demo_mysql -v f:/mysql/data:/var/lib/mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root mysql`
when I try to connect with java demo ,I get exeception
`Access denied for user 'root'@'localhost'`
when I try to test connection with mysql workbench , i get error
_failed to connect mysql at 127.0.0.1:3306 with user root,bad handshake_
but when I try to connect with cmd , it connect!
`mysql -P 3306 -uroot -p`

then I run another container binding port 3307,
`docker run -d --name demo_mysql2 -v f:/mysql/data2:/var/lib/mysql -p 3307:3306 -e MYSQL_ROOT_PASSWORD=root mysql`
they can all connect to the mysql in demo_mysql2!

**Comment by wglambert** [comment]
You'd have to troubleshoot the way your Java app and mysql workbench are connecting, it could also be that the container isn't ready to accept connections. I don't know how operable your bindmount is but that could also be an issue such as if you're using LCOW https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers#bind-mounts

This might be relevant for you https://bugs.mysql.com/bug.php?id=91828

But connecting remotely to the container works fine
```console
$ docker run -d --rm --network=net --name mysql -e MYSQL_ROOT_PASSWORD=pass mysql:5.7
6475f71c3f50dc76e4cef24fc18a2a9eb7e8d580e630fd3faed6f2c98da030ae

$ docker run -d --rm --network=net --name mysql_client -e MYSQL_ROOT_PASSWORD=pass mysql:5.7
0d2ec37a37a61d0a77eb67a090076139f8d5e40e462c0d2ee279f5670ae65365

$ docker ps | grep mysql
0d2ec37a37a6        mysql:5.7              "docker-entrypoint.s…"   About a minute ago   Up About a minute   3306/tcp, 33060/tcp   mysql_client
6475f71c3f50        mysql:5.7              "docker-entrypoint.s…"   2 minutes ago        Up 2 minutes        3306/tcp, 33060/tcp   mysql
```
Telling the `mysql_client` to connect to the other `mysql` container:
```console
$ docker exec -it mysql_client mysql -hmysql -uroot -ppass
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.7.26 MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
