### ISSUE TITLE
entrypoint fails on chown if there are readonly hidden files in the datadir

### ISSUE THREAD

**Issue by jeffbearer** [docker-library/mysql#587]
If there are readonly elements in the datadir like a .snapshot directory from a storage server the entrypoint fails on the [chown of the datadir](https://github.com/docker-library/mysql/blob/68f5102a73d8df4d739c20c581518850350794f6/5.7/docker-entrypoint.sh#L88) since the script is running the the -e shell option.

It can be worked around with adding a _|| true_ to that line.  or a more elegant solution may be desired.

`chown -R mysql:mysql "$DATADIR" || true`

**Comment by wglambert** [comment]
`mysql:5.7` and lower has an option for ignoring directories https://dev.mysql.com/doc/refman/5.7/en/server-options.html#option_mysqld_ignore-db-dir

Similar to the `lost+found` issue https://github.com/docker-library/mysql/issues/186

**Comment by yosifkit** [comment]
With a `.snapshot` directory, it seems that you don't hit the #186 problem since it is a "hidden" folder.

You could just skip the `chown` by setting a `--user` (compose: `user:`) to the (non-root) owner of the directory on the storage server.

Or you could use a subdirectory of your storage device so that `.snapshot` is next to the target of `/var/lib/mysql` rather than inside it.
