### ISSUE TITLE
mysql8 can't start

### ISSUE THREAD

**Issue by kay07** [docker-library/mysql#619]
in docker ,about mysql8.X,when I start mysql with the commant:

service mysql start 

or 

service mysqld start 

it can't start ,and get an error :

mysql: unrecognized service

**Comment by kay07** [comment]
But I mysql5.X,it can start ,why?

**Comment by wglambert** [comment]
They're both installed from source in the same way, so it's probably that mysql 8 doesn't make a sysvinit file, and there's no systemd in the container, but starting it from the binary will work

https://github.com/docker-library/mysql/blob/75f81c8e20e5085422155c48a50d99321212bf6f/8.0/Dockerfile#L75

**Comment by kay07** [comment]
> They're both installed from source in the same way, so it's probably that mysql 8 doesn't make a sysvinit file, and there's no systemd in the container, but starting it from the binary will work
> 
> https://github.com/docker-library/mysql/blob/75f81c8e20e5085422155c48a50d99321212bf6f/8.0/Dockerfile#L75

I'm sorry ,what you meaning is I start it with the comment "service mysqld start"?But it did'n work too.Or I should run the Dockerfile of mysql8?

**Comment by wglambert** [comment]
No when you do `service` it will look for a sysvinit script https://linux.die.net/man/8/service

In `mysql:8` there isn't a script in `/etc/init.d/` so to run `mysql` you would execute the binary at `/usr/sbin/mysqld`

I'm going to close since this isn't an issue with the image, if you have further questions you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
