### ISSUE TITLE
Health check fails when docker command is not mysqld.

### ISSUE THREAD

**Issue by dick-twocows** [docker-library/mysql#621]
Technically this is against mysql-cluster but there is no way to raise an issue...

The healthcheck.sh checks for the healthcheck.cnf to be touched, however this only happens when mysqld is called because the file is only touched in this if/endif block.

This means the management container and data containers are all marked unhealthy.

Either the script needs to be modified of the health check removed..?

**Comment by wglambert** [comment]
The [mysql-cluster](https://hub.docker.com/r/mysql/mysql-cluster/) image is pretty different from our `mysql` official-image. `mysql-cluster` is also maintained by "The MySQL team at Oracle". Their repo is at https://github.com/mysql/mysql-docker/tree/mysql-cluster

The readme notes: 
>Where to file issues: Please submit a bug report at http://bugs.mysql.com under the category “MySQL Package Repos and Docker Images”.

So we can't help you with an image that we don't maintain; healthchecks aren't included in the official-images that we maintain for reasons outlined https://github.com/docker-library/faq#healthcheck
We do have a healthcheck repo that provides examples for creating your own https://github.com/docker-library/healthcheck

But I'm going to close since that's not an image we maintain
