### ISSUE TITLE
port can't map to host

### ISSUE THREAD

**Issue by hbu-lijun** [docker-library/mysql#625]
The port can't map to host, I can't find the 3306 port on the host by using netstat command, i don't know why? I can find the mapping port (3306:33060) in starting container

**Comment by wglambert** [comment]
You have your ports backwards
https://docs.docker.com/config/containers/container-networking/#published-ports
>-p 8080:80 | Map TCP port 80 in the container to port 8080 on the Docker host.

For further help you should ask over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
