### ISSUE TITLE
How to stop and restart mysql server?

### ISSUE THREAD

**Issue by siddjain** [docker-library/mysql#630]
I need to stop mysql server and restart it with `--default-authentication-plugin=mysql_native_password`. How can I do this?

Normally I use `systemctl` to stop and start but `systemctl` is not there on the container. Neither can I find `/etc/init.d/mysql`

```
# ls /etc/init.d/mysql
ls: cannot access '/etc/init.d/mysql': No such file or directory
```

**Comment by wglambert** [comment]
`/etc/init.d/mysql` is for sysvinit which along with systemd, isn't in the container. There's a lot to cover about init systems, processes, and what is required for a container's function as to why that is. The official docs touch on that briefly https://docs.docker.com/config/containers/multi-service_container/

Essentially you just need to restart the container so when the server is started it will recognize the option. 

For further questions you should try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
