### ISSUE TITLE
/docker-entrypoint-initdb.d/ equivalent for scripts at every start?

### ISSUE THREAD

**Issue by shoooe** [docker-library/mysql#642]
**Feature**

Would it be possible to have a `/docker-entrypoint-initdb.d/` equivalent for scripts that should be run before the database is externally accessible at every container startup?

**Use case**

My specific use case is to run migration scripts at container startup.

**Implementation idea**

The way I'm imagining it is extending `docker-entrypoint.sh` so that:
 - it checks if a folder like `/docker-entrypoint-startdb.d/` (notice `startdb` instead of `initdb`) exists
 - starts the temp server if the database doesn't exist or if the database exists but the folder `/docker-entrypoint-startdb.d/` exists
 - runs every script inside the `/docker-entrypoint-startdb.d/` directory after the `/docker-entrypoint-initdb.d/` scripts

**Rationale**

It's very difficult to extend this image with this functionality without writing a custom `docker-entrypoint.sh` file (which would then not be updated when this image gets updated).

**Comment by wglambert** [comment]
Something like this https://github.com/docker-library/mariadb/issues/284#issue-550132097?
>run startup scripts on container restarts on existing (ie. not new) volumes.

**Comment by shoe-diamente** [comment]
Do you mean this: https://github.com/docker-library/mariadb/issues/284#issuecomment-575349157?

It's a possible solution but writing your own `docker-entrypoint.sh` is suboptimal. If this image's `docker-entrypoint.sh` changes (which seems to have happened between that comment and the current state of `docker-entrypoint.sh`) to introduce bug fixes or security fixes I won't get the benefits of those changes because I have my custom `docker-entrypoint.sh`.

Moreover is the API compatibility of bash functions in `docker-entrypoint.sh` guaranteed ? Will upgrading the image to a new minor version guarantee that those bash functions will still be there?

**Comment by yosifkit** [comment]
> Moreover is the API compatibility of bash functions in `docker-entrypoint.sh` guaranteed ? Will upgrading the image to a new minor version guarantee that those bash functions will still be there?

The functions not beginning with an underscore are considered the "public" interface of the script when sourcing it and so will be kept as a stable as possible (functionality, names, and arguments will be very unlikely to change). On the flip side, functions beginning with an underscore are "private" and can change at any time.

I am trying to work on documenting their intended functionality and any arguments, but haven't been able to get to it yet. The spreadsheet linked from #471 contains their current description and any discussion of their creation (and any that accept arguments should be commented in the function itself). 

- https://github.com/docker-library/mysql/pull/471#issuecomment-453262795 -> https://docs.google.com/spreadsheets/d/1yYlDjwHw58ng_9eZntI2PAuGGn_WgdatqUZQp5Ra-_s/edit?usp=sharing)

**Comment by wglambert** [comment]
Going to close as this seems sufficiently answered

**Comment by shoe-diamente** [comment]
Yeah I managed it, thanks.
