### ISSUE TITLE
Is it possible to restart mysql service without restart container?

### ISSUE THREAD

**Issue by EKwongChum** [docker-library/mysql#676]
While using this reposity's image  mysql:5.7 ,we may need to restart mysql some times. 
Once we call `service mysql restart` command ,the container restarts.
But we do not want the container restarts at that time.
Is it possible to restart mysql service without restart container? thx.

**Comment by wglambert** [comment]
Sysvinit and Systemd, aren't running in the container, so `mysql` is PID 1 and when it dies the container exits. If you wanted that behavior then you'd want to make a derivative Dockerfile to include an init system or another workaround of having a different process be PID 1, but that would also affect signals and logging. \

https://docs.docker.com/config/containers/multi-service_container/

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
