### ISSUE TITLE
AWS ECR scan detects vulnerabilities for mysql docker images 8.0 and above

### ISSUE THREAD

**Issue by pan-xuan** [docker-library/mysql#686]
When uploading mysql docker image version 8.0 above to AWS Elastic Container Registry, it reports two vulnerabilities that both linked to this following issue:

_Perl before 5.30.3 on 32-bit platforms allows a heap-based buffer overflow because nested regular expression quantifiers have an integer overflow._

The detailed report are below:
http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-10543
http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2020-10878

**Comment by pan-xuan** [comment]
can we run `apt-get install perl ` with a specific PERL version that is higher than 5.30? I don't have a debian system. Searching ubuntu however only demonstrates 5.26

**Comment by pan-xuan** [comment]
this issue seemed to be fix on debian:bullseye-slim

https://packages.debian.org/search?searchon=sourcenames&keywords=perl

can we upgrade the base image to bullseye?

**Comment by yosifkit** [comment]
We will not be upgrading to `bullseye` since it is still the "testing" release of Debian (https://www.debian.org/releases/bullseye/)

---

I am fairly certain that CVE-2020-10543 doesn't even apply to most users deploying on cloud providers.

> Perl before 5.30.3 on **32-bit platforms**

The Debian Security deemed the issue minor, so the fix for both issues will likely never be backported for Debian Buster.

> [buster] - perl <no-dsa> (Minor issue)
> \- https://security-tracker.debian.org/tracker/CVE-2020-10543
> \- https://security-tracker.debian.org/tracker/CVE-2020-10878

Also note that neither of these are fixed for RHEL (https://access.redhat.com/security/cve/CVE-2020-10878 https://access.redhat.com/security/cve/CVE-2020-10543). While it is no excuse for Debian that another Linux distribution is unpatched, when it is many it can be a good indication that the CVE's in question are not important or too intrusive to backport.

---

See also https://github.com/docker-library/faq/#why-does-my-security-scanner-show-that-an-image-has-cves
