### ISSUE TITLE
can not run container

### ISSUE THREAD

**Issue by trent87** [docker-library/mysql#699]
### ENV
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
2.9 GHz dual core Intel Core i5
16G  RAM
Docker Engine version:19.03.12
image:mysql:latest

it cost a lot at least 5 minutes to start container by command 'docker run -p 3306:3306 --name mysql -v /Users/data/mysql/conf:/etc/mysql/conf.d -v /Users/data/mysql/logs:/logs -v /Users/data/mysql/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456 -d mysql:latest' 
however mysql start faild for reason '2020-08-06T13:56:42.158899Z 0 [ERROR] [MY-010270] [Server] Can't start server : Bind on unix socket: File name too long'

**Comment by wglambert** [comment]
https://github.com/moby/moby/issues/23545#issuecomment-226144475
>There are issues with socket name lengths if the socket is being created on a volume shared with the Mac . . .

https://stackoverflow.com/a/62423664
>you need to find smallest folder path that works for your project.

Closing since this is a Docker for Mac issue and there's nothing we could change in the image to alleviate this problem.

If you need further help you could try searching through issues on https://github.com/moby/moby/issues or https://github.com/docker/for-mac/issues
Or asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
