### ISSUE TITLE
Where is MySQL 5.5.62 Dockerfile?

### ISSUE THREAD

**Issue by erfansahaf** [docker-library/mysql#705]
I'm wondering where is the Dockerfile for the 5.5.62 version? 

I couldn't find it on the root directory (only +5.6 versions exist). Neither in the repo tags.
Please guide me where I can find and read it's instructions and entrypoint.sh file.

I'm using the official image `mysql:5.5.62`.

**Comment by wglambert** [comment]
5.5 reached end of life December 3, 2018 and stopped receiving updates at that point https://github.com/docker-library/mysql/pull/566
https://en.wikipedia.org/wiki/MySQL#Release_history
https://endoflife.software/applications/databases/mysql

DockerHub still retains old images which is why you can pull it

Here's the old entrypoint https://github.com/docker-library/mysql/blob/3362baccb4352bcf0022014f67c1ec7e6808b8c5/5.5/docker-entrypoint.sh
And Dockerfile https://github.com/docker-library/mysql/blob/3362baccb4352bcf0022014f67c1ec7e6808b8c5/5.5/Dockerfile

**Comment by erfansahaf** [comment]
@wglambert Thank you for clarification.
