### ISSUE TITLE
Fails to run docker container 

### ISSUE THREAD

**Issue by The-Neo-Noir** [docker-library/mysql#706]
I copied into my own docker file , and build the image.  from 5.6 

When running the image 
`docker run -e MYSQL_ROOT_PASSWORD=my-secret-pw -e MYSQL_USER=test  -e MYSQL_PASSWORD=test  -e MYSQL_DATABASE=test  -d test-mysql:1.0.0 `

I get the following error. I don't know why 

`docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"entrypoint.sh\": executable file not found in $PATH": unknown.
`

**Comment by wglambert** [comment]
Your `docker run` works fine with `mysql:5.6` so the issue would be with your Dockerfile, which seems to be looking for `entrypoint.sh` which it can't find.
If you're wanting to use our entrypoint script then transplanting this line should work:
https://github.com/docker-library/mysql/blob/b0f81a33748561ae4e35a09895b2ad112ff89ba6/5.6/Dockerfile#L85

Ensuring you've built the image with the entrypoint file in the [build context](https://docs.docker.com/engine/reference/commandline/build/#extended-description) (default is just in the same directory as where you're executing `docker build`)

I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). And provide them your Dockerfile, since these repos aren't really a user-help forum

**Comment by yosifkit** [comment]
If you only downloaded the Dockerfile and entrypoint script instead of `git clone`, then the script would be missing the executable bit. So you need to `chmod +x` the `sh` file before doing `docker build`. Duplicate of https://github.com/docker-library/mysql/pull/311.
