### ISSUE TITLE
connect failed

### ISSUE THREAD

**Issue by ZhaoYi-Student** [docker-library/mysql#712]
connect failed when input "mysql -u  root -p"
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by yosoy-jorge** [comment]
install mysql client for linux on your host and in your container

**Comment by yosoy-jorge** [comment]
mysql -u root -h 127.0.0.1 -p

**Comment by rgargny** [comment]
I can connect fine from within docker bash
But when my client is not in docker:
mysql -u root -p -h0.0.0.0 -S /var/run/mysqld/mysqld.sock
Enter password: 
ERROR 2026 (HY000): SSL connection error: unknown error number

**Comment by xiamensink** [comment]
check your mysql status: `service mysql  status`
if print this:`[info] MySQL Community Server 5.7.31 is not running.`
use this:` service mysql start`

**Comment by yosifkit** [comment]
There is no `init` in the container so please do not use `service`/`systemctl` based commands, they will not be useful.

**Comment by yosifkit** [comment]
@ZhaoYi-Student, can you please provide the other commands that you ran as well as OS information?  This will allow others to know how you got to your error and help them pinpoint the issue.

**Comment by wglambert** [comment]
Going to close since there isn't enough information provided to troubleshoot the issue.
You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
