### ISSUE TITLE
Always restart with error "Assertion failure: dict0dict.cc"

### ISSUE THREAD

**Issue by olegKusov** [docker-library/mysql#759]
<img width="1148" alt="Снимок экрана 2021-04-10 в 13 18 26" src="https://user-images.githubusercontent.com/28058268/114266479-45b2fb80-99ff-11eb-9f37-ec6029450733.png">

Docker-compose config:
![image](https://user-images.githubusercontent.com/28058268/114266547-890d6a00-99ff-11eb-9b8c-d71de56d93b8.png)

When I delete files inside volume folder, it starts working well. But after few days this error appears and container restart always.
I thought that it's because container needs more RAM but when I increased RAM from 2 GB to 3 GB the error still remains.

OS: MacOS Big Sur
Macbook air 2017 with 8 GB of RAM.

**Comment by wglambert** [comment]
You could try disabling gRPC FUSE https://github.com/docker/for-mac/issues/4953#issuecomment-702448599

Otherwise maybe using a completely new volume could prevent the data from continuously getting corrupted, but I would also try asking over at the [Docker for Mac repo](https://github.com/docker/for-mac/issues/), [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since this doesn't seem to be an issue with the image so I don't think there's anything we could do at this level to alleviate the issue

**Comment by olegKusov** [comment]
> You could try disabling gRPC FUSE [docker/for-mac#4953 (comment)](https://github.com/docker/for-mac/issues/4953#issuecomment-702448599)
> 
> Otherwise maybe using a completely new volume could prevent the data from continuously getting corrupted, but I would also try asking over at the [Docker for Mac repo](https://github.com/docker/for-mac/issues/), [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since this doesn't seem to be an issue with the image so I don't think there's anything we could do at this level to alleviate the issue

yes, I tried to disable gRPC. it didn't help. Thank you
