### ISSUE TITLE
Fails to start when socket directory is in a Podman volume

### ISSUE THREAD

**Issue by o-alquimista** [docker-library/mysql#764]
If you put the socket directory in a volume using `podman`, the container won't start due to permissions on the socket directory being `root:root` instead of `mysql:mysql`. This seems to be caused by volume mountpoint permissions, as explained [here](https://github.com/MariaDB/mariadb-docker/issues/363).

So, the MariaDB official image has the same issue. I wonder if there's something you (the image developers) can do to fix this behavior. Otherwise I'll have to take this to the Podman developers, because it works with Docker.

**Comment by tianon** [comment]
We appropriately `chown` the MySQL `datadir` if we're started as root; I guess we could do the same for `/var/run/mysqld` (although I'd hesitate to do it for any arbitrary value of the `socket` configuration flag beyond this default, since that configuration value is not pointing at a directory so it's less clear that we should `chown` the whole thing):

https://github.com/docker-library/mysql/blob/919d1ce067be67fbeb1ff43e82c0a3153160ca28/template/docker-entrypoint.sh#L184-L187

**Comment by o-alquimista** [comment]
The thing is that I need to share the socket with a PHP container, setting ownership to something like `mysql:php` at build time.

Why can't I reproduce this issue with Docker? Is Podman overriding the permissions of the volume mountpoint while Docker is not? Maybe I should take this issue to Podman.

**Comment by o-alquimista** [comment]
I've found a simple solution for my problem. I described it [here](https://github.com/MariaDB/mariadb-docker/issues/363#issuecomment-824496833). Essentially, I'm using the `--user` argument to run MySQL as an arbitrary user.

You may close this issue if there's nothing else to do about it.

**Comment by tianon** [comment]
Sounds good, glad you got it sorted! :+1:
