### ISSUE TITLE
Issue with Increasing the max global connection

### ISSUE THREAD

**Issue by chsiva** [docker-library/mysql#765]
the connections increasing in the mysql docker looks like manual process but that wont work for everything it need to have some automation process to increasing connections

**Comment by wglambert** [comment]
You can pass `--max_connections=1000` as the [command to the image](https://github.com/docker-library/docs/tree/master/mysql#configuration-without-a-cnf-file), or supply a [`my.cnf`](https://github.com/docker-library/docs/tree/master/mysql#using-a-custom-mysql-configuration-file), or enter on the `mysql` command line `SET GLOBAL max_connections = 1000;` (which you could also have as a `.sql` script to be executed on initialization https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance)

**Comment by wglambert** [comment]
Going to close since this seems resolved, you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
