### ISSUE TITLE
MariaDB Audit plugin causes server to crash 

### ISSUE THREAD

**Issue by hpfish** [docker-library/mysql#768]
![image](https://user-images.githubusercontent.com/22662589/115981907-d7a73080-a5c9-11eb-8f06-1c9eaaaadd85.png)

**Comment by hpfish** [comment]
mysql 5.7.34

**Comment by wglambert** [comment]
If a plugin is causing the container to crash then I think asking the users/maintainers of that plugin for more information on what's happening would be the best option

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
