### ISSUE TITLE
Custom configuration files can be set server_id?

### ISSUE THREAD

**Issue by dousp** [docker-library/mysql#769]
#  Custom configuration files can be set server_id ?

- env is win

- docker shell
```
docker run --name dd `
-p 3336:3306 `
-e MYSQL_ROOT_PASSWORD=123456 `
-v /d/work/docker/mysql/test:/etc/mysql/conf.d `
-d mysql `
--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci `
--default-authentication-plugin=mysql_native_password --lower-case-table-names=1
```

- conf file
```
[mysqld]
server_id=21
```

- and  in mysql 
```
show  variables like 'server_id%' 
```

## question
- why 'server_id' always is 1 ?
- if add `--server-id=21`, server-id is 21

## solution
- enter the container to modify file permissions：` chmod 644 my.cnf`
- the server_id is changed to 21
- i tried it again on the mac, and it worked fine
- i think there may be some special Settings on Win10 that cause this problem

## the last
- When I create the container, is there any way I don't need input： `chmod 644 my.cnf`  ？？？

**Comment by yosifkit** [comment]
> why 'server_id' always is 1 ?

Default value for MySQL 8 is `1` (https://dev.mysql.com/doc/refman/8.0/en/replication-options.html)

 ---

Sharing files from Windows to a Linux container is not great (`-v /d/work/docker/mysql/test:/etc/mysql/conf.d`); which is why you had to adjust the permissions of the file so that it could be read by the `mysql` user in the container. I am uncertain if there are any settings in Docker for Windows that could solve the problem (I'd suggest trying dedicated forums or something like Stack Overflow for help on that).

One option is to just build an image with the custom config built-in:
```dockerfile
FROM mysql:8
COPY --chown=mysql:mysql test/ /etc/mysql/conf.d/
# might need to fix permissions?
#RUN chmod 660 /etc/mysql/conf.d/*.cnf
```

Or just put all the config in the arguments (which can be embedded in deplotment configuration like `docker-compose.yml` or Kubernetes deployment yaml):
```console
$ docker run ... mysql:8 --server-id=9001 ...
```

**Comment by dousp** [comment]
> why 'server_id' always is 1 ?
- I actually want to express why I didn't change the default 1 after I set it through the configuration file.

After reading your reply，it is a good idea to build an image with the custom config.
