### ISSUE TITLE
SSPI error in MySQL under vs2017 linked docker

### ISSUE THREAD

**Issue by zxxiao2012** [docker-library/mysql#777]
Call to SSPI failed, see inner exception，why,how to do?

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant files or logs for reproducing the issue

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
