### ISSUE TITLE
MySQL 5.5 image doesn't have libmysqlclient-dev package

### ISSUE THREAD

**Issue by DimitriosLisenko** [docker-library/mysql#788]
The images for MySQL 5.6, 5.7, and 8.0 all seem to have the libmysqlclient-dev package present for the specific version of MySQL from the MySQL repository. For example:
```
# apt-get update > /dev/null && apt-cache policy libmysqlclient-dev
libmysqlclient-dev:
  Installed: (none)
  Candidate: 5.6.51-1debian9
  Version table:
     5.6.51-1debian9 500
        500 http://repo.mysql.com/apt/debian stretch/mysql-5.6 amd64 Packages
```

However, running the above for the MySQL 5.5 image results in the following:
```
# apt-get update > /dev/null && apt-cache policy libmysqlclient-dev
libmysqlclient-dev:
  Installed: (none)
  Candidate: (none)
  Version table:
```

There are some suggestions online to use `default-libmysqlclient-dev`, but that doesn't seem right to me because that's the one that comes with Debian and is not specific to a MySQL version unlike the others. Also, until recently, it did seem to work for MySQL 5.5 as well. Any suggestions would be appreciated.

**Comment by tianon** [comment]
Unfortunately MySQL 5.5 has been EOL and unsupported since https://github.com/docker-library/mysql/commit/98f958b67cf45af464c3ad4521a1e2af71398650 (#566).

The cause of what you're seeing is that for 5.5 we had to download the upstream tarballs instead of installing packages:

https://github.com/docker-library/mysql/blob/3362baccb4352bcf0022014f67c1ec7e6808b8c5/5.5/Dockerfile#L44-L54

(So what you're looking for unfortunately wasn't ever part of the 5.5 images. :disappointed:)

**Comment by DimitriosLisenko** [comment]
Understood, thank you for your response!
