### ISSUE TITLE
Missing yum in latest image

### ISSUE THREAD

**Issue by psfabq** [docker-library/mysql#823]
I inherited a mysql jenkins build pipeline with a Dockerfile that expects yum in the image for performing updates. Are there any plans to add back that package? Thank yoiu

**Comment by yosifkit** [comment]
The current images are based on Debian and so have never had `yum`.

Do you mean the [`mysql/mysql-server`](https://hub.docker.com/r/mysql/mysql-server) images? Those are not built from here, but from over in https://github.com/mysql/mysql-docker. If you are using the `latest` tag over there, then you probably need to use `microdnf` instead of `yum` since it has moved to [`oraclelinux:8`](https://github.com/mysql/mysql-docker/blob/1bc29fbe22d1afc8475b378068b59a6fb48732e7/mysql-server/8.0/Dockerfile) instead of `oraclelinux:7`.
