### ISSUE TITLE
mysql-first-time fails to run when custom cnf configuration has client protocol=TCP

### ISSUE THREAD

**Issue by joshunger** [docker-library/mysql#83]
mysql-first-time fails to run when custom cnf configuration has client protocol=TCP

1. Create custom MySQL configuration file with the following content -

```
[client]
protocol=tcp
```

2. Start mysql docker using the instructions from https://github.com/docker-library/docs/tree/master/mysql#user-content-using-a-custom-mysql-configuration-file

EXPECTING: mysql-first-time script runs

ACTUAL: fails with the following error -

ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost' (111)

See line 81 https://github.com/docker-library/mysql/blob/master/5.6/docker-entrypoint.sh.  Shouldn't the protocol be forced to something other than TCP since mysqld was started with skip-networking?

**Comment by tianon** [comment]
ping @ltangvald; what're your thoughts on the best way to handle this?

**Comment by ltangvald** [comment]
For this single issue we could probably override the socket option when running the client during init (will test this).
The bigger issue is that there are any number of settings that can probably break init of the image. But at the same time we don't want to insulate it completely from custom config, since some settings are needed during database creation.
There's a risk we could end up with a steadily growing number of overrides, but might be simpler that handle that issue when and if it appears.

**Comment by ltangvald** [comment]
So the override works, but it highlights another issue: The 5.5-image uses /etc/mysql/conf.d/docker.cnf to store default datadir and user settings, and the user setting in particular is required for the server to start. Should probably move these settings to etc/mysql/my.cnf instead.
