### ISSUE TITLE
What to do when the mysql configuration file cannot be found

### ISSUE THREAD

**Issue by KwonDoHyuk** [docker-library/mysql#848]
Ubuntu 20.04 LTS
mysql:latest

Hi. I'm not good at English, so please understand if I make a mistake.
I Download and run mysql with docker on ubuntu.
There is a problem in the process of connecting springboot and mysql, and we are looking for the cause.
Among them, I am looking for a configuration file to set "bind-address = 0.0.0.0".

but i cant find
`/etc/mysql/my.cnf`
to find it, I entered the following command
`sudo find / -name 'my.cnf'
`
and the result is that 
`
/var/lib/docker/overlay2/765c243fd940bca459bdb4b93162e3a07dbac4734b572b76027ec014caca21e9/merged/var/lib/dpkg/alternatives/my.cnf
/var/lib/docker/overlay2/765c243fd940bca459bdb4b93162e3a07dbac4734b572b76027ec014caca21e9/merged/etc/alternatives/my.cnf
/var/lib/docker/overlay2/765c243fd940bca459bdb4b93162e3a07dbac4734b572b76027ec014caca21e9/merged/etc/mysql/my.cnf
/var/lib/docker/overlay2/23f84c7f94b4947b8479e0299bc7105a6dbe18881b8154e62879460304007ddc/diff/var/lib/dpkg/alternatives/my.cnf
/var/lib/docker/overlay2/23f84c7f94b4947b8479e0299bc7105a6dbe18881b8154e62879460304007ddc/diff/etc/mysql/my.cnf
/var/lib/docker/overlay2/23f84c7f94b4947b8479e0299bc7105a6dbe18881b8154e62879460304007ddc/diff/etc/alternatives/my.cnf
/var/lib/docker/overlay2/1508aa0426458b16fc468bf568d031cd648df97646ddfdab36d260431b1c7d55/diff/etc/mysql/my.cnf
/var/lib/docker/overlay2/3d6f2c9d0a1c5cfa9758c14a98b50a57b9df1e70c7a1a9e1fff077802c817d32/diff/var/lib/dpkg/alternatives/my.cnf
/var/lib/docker/overlay2/3d6f2c9d0a1c5cfa9758c14a98b50a57b9df1e70c7a1a9e1fff077802c817d32/diff/etc/mysql/my.cnf
/var/lib/docker/overlay2/3d6f2c9d0a1c5cfa9758c14a98b50a57b9df1e70c7a1a9e1fff077802c817d32/diff/etc/alternatives/my.cnf
/var/lib/docker/overlay2/46b10b751d8f6fef2cce281a355049b350d3d3b26eefc5fd78021ff161414255/merged/var/lib/dpkg/alternatives/my.cnf
/var/lib/docker/overlay2/46b10b751d8f6fef2cce281a355049b350d3d3b26eefc5fd78021ff161414255/merged/etc/alternatives/my.cnf
/var/lib/docker/overlay2/46b10b751d8f6fef2cce281a355049b350d3d3b26eefc5fd78021ff161414255/merged/etc/mysql/my.cnf
`
But I couldn't find the desired config file
How can i find 'my.cnf' to add 'bind-address= 0.0.0.0' with docker.

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/mysql#using-a-custom-mysql-configuration-file

Running `sudo find / -name 'my.cnf'` outside of the container isn't relevant to the container's environment

```console
$ docker run -d --rm --name mysql -e MYSQL_ROOT_PASSWORD=pass mysql
9dba35f720e0f178ac0ef9aba8bf2f37dd5ee457d6956ab3b8fa984e2bb0a13b

$ docker exec -it mysql bash
root@9dba35f720e0:/# find / | grep -i my.cnf
/var/lib/dpkg/alternatives/my.cnf
/etc/alternatives/my.cnf
/etc/mysql/my.cnf.fallback
/etc/mysql/my.cnf

root@9dba35f720e0:/# mysqld --verbose --help 2>&1 | grep bind-address
  --bind-address=name IP address(es) to bind to. Syntax: address[,address]...,
  --mysqlx-bind-address[=name]
bind-address                                                 *
mysqlx-bind-address                                          *
```

By default the bind-address is set to `*`
If you want to connect to it externally you'll want to [publish](https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose) the port like `docker run -p 3306:3306 -d --rm --name mysql -e MYSQL_ROOT_PASSWORD=pass mysql`

In the future questions like these are better asked over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
