### ISSUE TITLE
Can not connect to mysql:8.0.30-debian and mysql:8.0.28-debian via MySQL Workbench.

### ISSUE THREAD

**Issue by behai-nguyen** [docker-library/mysql#899]
I can't connect to MySQL server using **mysql:8.0.30-debian** and **mysql:8.0.28-debian** images. While I can connect to **mysql:5.7.39-debian**.

#### My environments

1. Windows 10 Pro -- version 10.0.19044 build 19044. 
2. Docker client -- version 20.10.17.
3. Docker Desktop -- 4.11.0 (83626). Engine version 20.10.17.
4. MySQL Workbench -- version 6.3.0 build 12092614 (64 bits) community.

#### Connect to MySQL Workbench with:

```
Host: localhost
Port: 3306
User: root
Password: pcb.2176310315865259
```

#### mysql:8.0.30-debian

```
E:\>docker run --name mysql-docker -p 3306:3306 -e MYSQL_ROOT_PASSWORD=pcb.2176310315865259 --rm mysql:8.0.30-debian
```

**Failed**. Error message: **SSL connection error: unknown error number**.

#### mysql:8.0.28-debian

```
E:\>docker run --name mysql-docker -p 3306:3306 -e MYSQL_ROOT_PASSWORD=pcb.2176310315865259 --rm mysql:8.0.28-debian
```

**Failed**. Error message: **SSL connection error: unknown error number**.

#### mysql:5.7.39-debian

```
E:\>docker run --name mysql-docker -p 3306:3306 -e MYSQL_ROOT_PASSWORD=pcb.2176310315865259 --rm mysql:5.7.39-debian
```

This **mysql:5.7.39-debian** works.

**Comment by wglambert** [comment]
Using `--default-authentication-plugin=mysql_native_password` might fix it? 
https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password-compatibility-issues

But since the issue is with using MySQL Workbench I'd try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
