### ISSUE TITLE
Problems with /var/lib/mysql mounting directory in Persistent Volume EBS for EKS Cluster  

### ISSUE THREAD

**Issue by ejaramillo2** [docker-library/mysql#933]
When create Persitent Volume Claim with Storage Class EBS woth the driver CSI EBS, the mounted directory when finish formating create lost+found directory, this event causes the init process for create init mysql files 
not done correctly. All the documentation about this, say we needed more permissions for delete lost+found directory, but any tiem say permission denied. Can init files created with the lost+found directory?

**Comment by tianon** [comment]
When providing a raw formatted disk, you'll either need to use something like https://github.com/docker-library/mysql/issues/186#issuecomment-229480846 or (better) use a subdirectory of the newly formatted disk instead of providing the entire root (which provides some other benefits/flexibility as well).

In the future, these sorts of questions/requests would be more appropriately posted to a dedicated support forum, such as [the Docker Community Slack](https://dockr.ly/comm-slack), [Server Fault](https://serverfault.com/help/on-topic), [Unix & Linux](https://unix.stackexchange.com/help/on-topic), or [Stack Overflow](https://stackoverflow.com/help/on-topic).
