### ISSUE TITLE
request image for mysql 8.1.0 and 5.7.43

### ISSUE THREAD

**Issue by qeepcologne** [docker-library/mysql#988]
there are no debian/ubuntu packages provided anymore for 5.7.43, so oracle only is ok for me.

**Comment by yosifkit** [comment]
We've just started discussing what to do about the `5.7.43` update (since the update script currently insists that Debian and Oracle remain in sync) in https://github.com/docker-library/mysql/pull/987.  We'd love to add `8.1` but it is not in the APT or Yum repos.

Moving discussion there since it is relevant to the changes added.
